/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ea49e565-2f96-4232-8d7f-efde3ab130b5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_QrEmvCv9P",
    "aws_user_pools_web_client_id": "6jv4fd394vts6m73a6eojbkfcj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://itbh2h5xgjhzxanrczjpdjzrdq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qnetxbaanre3xlw3pngul4git4",
    "aws_user_files_s3_bucket": "amplifyapp21690cdfd0ba4f228df4ee12c4c2ee70134048-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
